#ifndef ADS112C04_CORE_DEFINES_
#define ADS112C04_CORE_DEFINES_

//AUXILIARY
#define BITS_1  0x01
#define BITS_2  0x03
#define BITS_3  0x07
#define BITS_4  

#define SENSOR_INIT_DELAY_MS  500

//SENSOR COMANDS
#define COMMAND_RESET           0x06
#define COMMAND_READ_DATA       0x10
#define COMMAND_READ_REGISTER   0x20 
#define COMMAND_WRITE_REGISTER  0x40
#define COMMAND_POWER_DOWN      0x02
#define COMMAND_START_OR_SYNC   0x08

//CONFIG REGISTERS TO MERGE WITH REGISTER COMMANDS:  |register_address|bit no matters|bit no matters|
#define CONFIG_REGISTER_0_CM    0x00  //  00xx
#define CONFIG_REGISTER_1_CM    0x04  //  01xx

//CONFIG1 REGISTER
#define VOLTAGE_REFERENCE_SELECTION_BITS    BITS_2
#define VOLTAGE_REFERENCE_SELECTION_SHIFT   1
#define VOLTAGE_REFERENCE_SELECTION_MASK    (VOLTAGE_REFERENCE_SELECTION_BITS << VOLTAGE_REFERENCE_SELECTION_SHIFT)
#define CONVERSION_MODE_BITS                BITS_1
#define CONVERSION_MODE_SHIFT               3
#define CONVERSION_MODE_MASK                (CONVERSION_MODE_BITS << CONVERSION_MODE_SHIFT)
#define OPERATION_MODE_BITS                 BITS_1
#define OPERATION_MODE_SHIFT                4
#define OPERATION_MODE_MASK                 (OPERATION_MODE_BITS << OPERATION_MODE_SHIFT) 
#define DATA_RATE_SELECTION_BITS            BITS_3
#define DATA_RATE_SELECTION_SHIFT           5
#define DATA_RATE_SELECTION_MASK           (DATA_RATE_SELECTION_BITS << DATA_RATE_SELECTION_SHIFT)

#endif